import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import styles from "../styles/Home.module.css";
import { GameCore } from "@/game-core/main";

export default function Home() {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const gameCore = GameCore;
  useEffect(() => {
    gameCore(canvasRef);
  }, [gameCore]);

  return (
    <>
      <Head>
        <title>Next Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={``}>
        <div style={{ minWidth: 1280 }}>
          <canvas
            style={{ minWidth: 1280 }}
            ref={canvasRef}
            className={styles.mainCanvas}
            height={720}
            width={1280}
          ></canvas>
        </div>
      </main>
    </>
  );
}
